CREATE TABLE public.sub_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  name TEXT NOT NULL,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  is_visible BOOLEAN NOT NULL DEFAULT true
);

ALTER TABLE public.sub_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view visible sub-categories"
ON public.sub_categories
FOR SELECT
USING (is_visible = true);

CREATE POLICY "Admins can manage sub-categories"
ON public.sub_categories
FOR ALL
USING ((( SELECT profiles.role
   FROM profiles
  WHERE (profiles.id = auth.uid())) = 'adm'::text));