CREATE TABLE public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_approved BOOLEAN NOT NULL DEFAULT true,
  UNIQUE (product_id, user_id, order_id) -- Garante que um usuário só pode avaliar um produto por pedido uma vez
);

-- Habilita RLS
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Política: Todos podem ver as avaliações aprovadas.
CREATE POLICY "Public can view approved reviews" ON public.reviews
  FOR SELECT USING (is_approved = true);

-- Política: Usuários podem inserir avaliações para seus próprios pedidos.
CREATE POLICY "Users can insert their own reviews" ON public.reviews
  FOR INSERT WITH CHECK (
    auth.uid() = user_id AND
    EXISTS (
      SELECT 1 FROM public.orders
      WHERE orders.id = reviews.order_id AND orders.user_id = auth.uid()
    )
  );

-- Política: Usuários podem atualizar suas próprias avaliações.
CREATE POLICY "Users can update their own reviews" ON public.reviews
  FOR UPDATE USING (auth.uid() = user_id);

-- Política: Admins podem gerenciar todas as avaliações.
CREATE POLICY "Admins can manage all reviews" ON public.reviews
  FOR ALL USING ((( SELECT profiles.role
   FROM profiles
  WHERE (profiles.id = auth.uid())) = 'adm'::text));