DROP TABLE IF EXISTS public.battles CASCADE;
DROP TABLE IF EXISTS public.chests CASCADE;
DROP TABLE IF EXISTS public.nfts CASCADE;
DROP TABLE IF EXISTS public.ships CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;