-- Tabela para armazenar popups de prova social (vendas recentes)
CREATE TABLE public.sales_popups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_image_url TEXT,
  time_ago TEXT NOT NULL, -- Ex: '5 minutos atrás'
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS (Obrigatório)
ALTER TABLE public.sales_popups ENABLE ROW LEVEL SECURITY;

-- Políticas de segurança: Apenas administradores podem gerenciar (INSERT, UPDATE, DELETE)
CREATE POLICY "Admin full access to sales_popups" ON public.sales_popups 
FOR ALL TO authenticated USING ((SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = 'adm'::text) WITH CHECK ((SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = 'adm'::text);

-- Política de leitura: Todos podem ler os popups ativos
CREATE POLICY "Public read active sales_popups" ON public.sales_popups 
FOR SELECT USING (is_active = TRUE);