-- Tabela de Sabores
CREATE TABLE public.flavors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  is_visible BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE public.flavors ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para Sabores
CREATE POLICY "Public read access for flavors" ON public.flavors 
FOR SELECT USING (is_visible = TRUE OR (SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = 'adm');

CREATE POLICY "Admin full access for flavors" ON public.flavors 
FOR ALL TO authenticated USING ((SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = 'adm') WITH CHECK ((SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = 'adm');

-- Tabela de Relação Produto-Sabor
CREATE TABLE public.product_flavors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  flavor_id BIGINT NOT NULL REFERENCES public.flavors(id) ON DELETE CASCADE,
  is_visible BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE (product_id, flavor_id)
);

-- Habilitar RLS
ALTER TABLE public.product_flavors ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para Relação Produto-Sabor
-- Usuários podem ler se o produto e o sabor estiverem visíveis
CREATE POLICY "Public read access for product_flavors" ON public.product_flavors 
FOR SELECT USING (is_visible = TRUE AND (SELECT is_visible FROM products WHERE id = product_flavors.product_id) = TRUE AND (SELECT is_visible FROM flavors WHERE id = product_flavors.flavor_id) = TRUE);

-- Admin full access
CREATE POLICY "Admin full access for product_flavors" ON public.product_flavors 
FOR ALL TO authenticated USING ((SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = 'adm') WITH CHECK ((SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = 'adm');

-- Inserindo alguns sabores iniciais
INSERT INTO public.flavors (name) VALUES 
('Menta'), 
('Morango'), 
('Cítrico'), 
('Doce'), 
('Tabaco');