-- Tabela principal do pedido de compra
CREATE TABLE public.supplier_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pendente', -- Pendente, Recebido, Cancelado
  total_cost NUMERIC(10,2) DEFAULT 0,
  notes TEXT,
  order_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Itens do pedido de compra (ligados aos seus produtos)
CREATE TABLE public.supplier_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_order_id BIGINT REFERENCES public.supplier_orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL,
  unit_cost NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE public.supplier_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_order_items ENABLE ROW LEVEL SECURITY;

-- Permissões apenas para administradores
CREATE POLICY "Admin full access for supplier_orders" ON public.supplier_orders 
FOR ALL TO authenticated USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm');

CREATE POLICY "Admin full access for supplier_order_items" ON public.supplier_order_items 
FOR ALL TO authenticated USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm');