CREATE TABLE IF NOT EXISTS public.data_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_type TEXT NOT NULL, -- 'import_clients', 'export_clients'
  status TEXT NOT NULL, -- 'success', 'error'
  summary TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id)
);

ALTER TABLE public.data_jobs ENABLE ROW LEVEL SECURITY;

-- Política para Admins verem e criarem logs
CREATE POLICY "Admins can view data_jobs" ON public.data_jobs
  FOR SELECT
  USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm');

CREATE POLICY "Admins can insert data_jobs" ON public.data_jobs
  FOR INSERT
  WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm');