-- Tabela para armazenar os itens que compõem um kit/promoção
CREATE TABLE public.promotion_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promotion_id BIGINT REFERENCES public.promotions(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  variant_id UUID REFERENCES public.product_variants(id) ON DELETE SET NULL, -- Opcional: se for um sabor específico
  quantity INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE public.promotion_items ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso (Admins gerenciam, Público apenas leitura se necessário, mas geralmente é backend)
CREATE POLICY "Admin full access promotion_items" ON public.promotion_items
  FOR ALL
  TO authenticated
  USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm')
  WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm');

CREATE POLICY "Public read promotion_items" ON public.promotion_items
  FOR SELECT
  TO anon, authenticated
  USING (true);