CREATE TABLE IF NOT EXISTS public.webhook_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trigger_event TEXT NOT NULL, -- 'order_created', 'payment_confirmed', etc.
  target_url TEXT NOT NULL,
  description TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.webhook_configs ENABLE ROW LEVEL SECURITY;

-- Apenas admins podem ver e editar
CREATE POLICY "Admins can manage webhooks" ON public.webhook_configs
  USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm'
  )
  WITH CHECK (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm'
  );