-- 1. Tabela de Configuração dos Níveis
CREATE TABLE public.loyalty_tiers (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL, -- Bronze, Prata, Ouro...
    min_spend NUMERIC NOT NULL, -- 0, 600, 1200...
    max_spend NUMERIC, -- 599, 1199... (NULL para o último nível)
    points_multiplier NUMERIC DEFAULT 1.0, -- 1.0, 1.5, 2.0
    benefits JSONB DEFAULT '[]'::jsonb, -- Lista de benefícios para exibir no front
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Inserir os Níveis definidos
INSERT INTO public.loyalty_tiers (name, min_spend, max_spend, points_multiplier, benefits) VALUES
('Bronze', 0, 599.99, 1.0, '["1 ponto por R$1"]'),
('Prata', 600, 1199.99, 1.0, '["1 ponto por R$1", "Frete grátis 1 dia/semana"]'),
('Ouro', 1200, 2399.99, 1.0, '["1 ponto por R$1", "Frete grátis 1 dia/semana", "Acesso antecipado"]'),
('Diamante', 2400, 3999.99, 1.5, '["1.5 pontos por R$1", "Brinde Anual", "Atendimento Prioritário", "Frete grátis 2 dias/semana"]'),
('Black', 4000, NULL, 2.0, '["2 pontos por R$1", "Frete Grátis Sempre", "Brindes Recorrentes", "Pré-venda Privada", "Presente Aniversário"]');

-- 2. Tabela de Histórico de Pontos (Extrato)
CREATE TABLE public.loyalty_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    points INTEGER NOT NULL, -- Pode ser positivo (ganho) ou negativo (resgate)
    description TEXT NOT NULL, -- "Compra #123", "Bônus Aniversário", "Resgate Cupom"
    operation_type TEXT NOT NULL, -- 'earn', 'redeem', 'adjustment'
    related_order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Atualizar Tabela de Perfis
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS tier_id INT REFERENCES public.loyalty_tiers(id) DEFAULT 1,
ADD COLUMN IF NOT EXISTS current_tier_name TEXT DEFAULT 'Bronze',
ADD COLUMN IF NOT EXISTS spend_last_6_months NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS birth_date_locked BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS last_tier_update TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Habilitar RLS
ALTER TABLE public.loyalty_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loyalty_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Leitura pública de níveis" ON public.loyalty_tiers FOR SELECT USING (true);
CREATE POLICY "Usuário vê seu histórico" ON public.loyalty_history FOR SELECT TO authenticated USING (auth.uid() = user_id);