-- Create shipping_rates table
CREATE TABLE IF NOT EXISTS public.shipping_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name TEXT NOT NULL, -- Ex: "Centro", "Zona Sul", "São Paulo"
    price NUMERIC NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.shipping_rates ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public read access for shipping rates" ON public.shipping_rates
    FOR SELECT USING (true);

CREATE POLICY "Admin full access for shipping rates" ON public.shipping_rates
    FOR ALL USING (
        (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm'
    );