-- 1. Garante que a tabela existe com a estrutura correta
CREATE TABLE IF NOT EXISTS public.shipping_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Adiciona constraint única para evitar duplicatas (se não existir)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'shipping_rates_location_name_key') THEN
        ALTER TABLE public.shipping_rates ADD CONSTRAINT shipping_rates_location_name_key UNIQUE (location_name);
    END IF;
END $$;

-- 3. Garante que as políticas de segurança (RLS) existam
ALTER TABLE public.shipping_rates ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read access for shipping rates') THEN
        CREATE POLICY "Public read access for shipping rates" ON public.shipping_rates FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admin full access for shipping rates') THEN
        CREATE POLICY "Admin full access for shipping rates" ON public.shipping_rates FOR ALL USING (
            (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm'
        );
    END IF;
END $$;

-- 4. Insere os bairros (ignorando se já existirem para não dar erro)
INSERT INTO public.shipping_rates (location_name, price, is_active)
VALUES 
  ('Abranches', 0, true),
  ('Água Verde', 0, true),
  ('Ahú', 0, true),
  ('Alto Boqueirão', 0, true),
  ('Alto da Glória', 0, true),
  ('Alto da XV', 0, true),
  ('Atuba', 0, true),
  ('Augusta', 0, true),
  ('Bacacheri', 0, true),
  ('Bairro Alto', 0, true),
  ('Barreirinha', 0, true),
  ('Batel', 0, true),
  ('Bigorrilho', 0, true),
  ('Boa Vista', 0, true),
  ('Bom Retiro', 0, true),
  ('Boqueirão', 0, true),
  ('Butiatuvinha', 0, true),
  ('Cabral', 0, true),
  ('Cachoeira', 0, true),
  ('Cajuru', 0, true),
  ('Campina do Siqueira', 0, true),
  ('Campo Comprido', 0, true),
  ('Campo de Santana', 0, true),
  ('Capão Raso', 0, true),
  ('Capão da Imbuia', 0, true),
  ('Cascatinha', 0, true),
  ('Caximba', 0, true),
  ('Centro', 0, true),
  ('Centro Cívico', 0, true),
  ('Cidade Industrial', 0, true),
  ('Cristo Rei', 0, true),
  ('Fanny', 0, true),
  ('Fazendinha', 0, true),
  ('Ganchinho', 0, true),
  ('Guabirotuba', 0, true),
  ('Guaíra', 0, true),
  ('Hauer', 0, true),
  ('Hugo Lange', 0, true),
  ('Jardim Botânico', 0, true),
  ('Jardim Social', 0, true),
  ('Jardim das Américas', 0, true),
  ('Juvevê', 0, true),
  ('Lamenha Pequena', 0, true),
  ('Lindóia', 0, true),
  ('Mercês', 0, true),
  ('Mossunguê', 0, true),
  ('Novo Mundo', 0, true),
  ('Orleans', 0, true),
  ('Parolin', 0, true),
  ('Pilarzinho', 0, true),
  ('Pinheirinho', 0, true),
  ('Portão', 0, true),
  ('Prado Velho', 0, true),
  ('Rebouças', 0, true),
  ('Riviera', 0, true),
  ('Santa Cândida', 0, true),
  ('Santa Felicidade', 0, true),
  ('Santa Quitéria', 0, true),
  ('Santo Inácio', 0, true),
  ('São Braz', 0, true),
  ('São Francisco', 0, true),
  ('São João', 0, true),
  ('São Lourenço', 0, true),
  ('São Miguel', 0, true),
  ('Seminário', 0, true),
  ('Sítio Cercado', 0, true),
  ('Taboão', 0, true),
  ('Tarumã', 0, true),
  ('Tatuquara', 0, true),
  ('Tingui', 0, true),
  ('Uberaba', 0, true),
  ('Umbará', 0, true),
  ('Vila Izabel', 0, true),
  ('Vista Alegre', 0, true),
  ('Xaxim', 0, true)
ON CONFLICT (location_name) DO NOTHING;