INSERT INTO public.shipping_rates (neighborhood, city, price, is_active)
VALUES 
  ('Academia', 'São José dos Pinhais', 0, true),
  ('Afonso Pena', 'São José dos Pinhais', 0, true),
  ('Águas Belas', 'São José dos Pinhais', 0, true),
  ('Área Institucional Aeroportuária', 'São José dos Pinhais', 0, true),
  ('Aristocrata', 'São José dos Pinhais', 0, true),
  ('Arujá', 'São José dos Pinhais', 0, true),
  ('Aviação', 'São José dos Pinhais', 0, true),
  ('Barro Preto', 'São José dos Pinhais', 0, true),
  ('Bom Jesus', 'São José dos Pinhais', 0, true),
  ('Boneca do Iguaçu', 'São José dos Pinhais', 0, true),
  ('Borda do Campo', 'São José dos Pinhais', 0, true),
  ('Cachoeira', 'São José dos Pinhais', 0, true),
  ('Campina do Taquaral', 'São José dos Pinhais', 0, true),
  ('Campo Largo da Roseira', 'São José dos Pinhais', 0, true),
  ('Centro', 'São José dos Pinhais', 0, true),
  ('Cidade Jardim', 'São José dos Pinhais', 0, true),
  ('Colônia Rio Grande', 'São José dos Pinhais', 0, true),
  ('Costeira', 'São José dos Pinhais', 0, true),
  ('Cristal', 'São José dos Pinhais', 0, true),
  ('Cruzeiro', 'São José dos Pinhais', 0, true),
  ('Del Rey', 'São José dos Pinhais', 0, true),
  ('Dom Rodrigo', 'São José dos Pinhais', 0, true),
  ('Guatupê', 'São José dos Pinhais', 0, true),
  ('Iná', 'São José dos Pinhais', 0, true),
  ('Ipê', 'São José dos Pinhais', 0, true),
  ('Itália', 'São José dos Pinhais', 0, true),
  ('Jurema', 'São José dos Pinhais', 0, true),
  ('Murici Urbano', 'São José dos Pinhais', 0, true),
  ('Ouro Fino', 'São José dos Pinhais', 0, true),
  ('Parque da Fonte', 'São José dos Pinhais', 0, true),
  ('Pedro Moro', 'São José dos Pinhais', 0, true),
  ('Quissisana', 'São José dos Pinhais', 0, true),
  ('Rio Pequeno', 'São José dos Pinhais', 0, true),
  ('Roseira de São Sebastião', 'São José dos Pinhais', 0, true),
  ('Santo Antônio', 'São José dos Pinhais', 0, true),
  ('São Cristóvão', 'São José dos Pinhais', 0, true),
  ('São Domingos', 'São José dos Pinhais', 0, true),
  ('São Pedro', 'São José dos Pinhais', 0, true),
  ('Zacarias', 'São José dos Pinhais', 0, true)
ON CONFLICT (neighborhood, city) DO NOTHING;