-- Tabela para permitir que um produto tenha várias subcategorias
CREATE TABLE IF NOT EXISTS public.product_sub_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  sub_category_id BIGINT REFERENCES public.sub_categories(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(product_id, sub_category_id)
);

-- Ativando RLS
ALTER TABLE public.product_sub_categories ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso
CREATE POLICY "Admins can manage product sub categories" ON public.product_sub_categories
FOR ALL TO authenticated USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm'
);

CREATE POLICY "Public can read product sub categories" ON public.product_sub_categories
FOR SELECT TO public USING (true);