// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jrlozhhvwqfmjtkmvukf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpybG96aGh2d3FmbWp0a212dWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDU2NjQsImV4cCI6MjA2NzkyMTY2NH0.Do5c1-TKqpyZTJeX_hLbw1SU40CbwXfCIC-pPpcD_JM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Função auxiliar para extrair o project ID da URL
function extractProjectId(url: string): string {
  const match = url.match(/https:\/\/([^.]+)\.supabase\.co/);
  return match ? match[1] : 'default';
}

// Storage seguro com fallback para memória — necessário para iOS Safari
// em modo de navegação privada e WebViews (WhatsApp, Instagram, etc.)
// onde window.localStorage pode lançar exceção ou estar indisponível.
function createSafeStorage() {
  try {
    const testKey = '__sb_storage_test__';
    window.localStorage.setItem(testKey, '1');
    window.localStorage.removeItem(testKey);
    return window.localStorage;
  } catch {
    // Fallback: storage em memória. A sessão não persiste entre abas,
    // mas a aplicação não quebra.
    const mem: Record<string, string> = {};
    return {
      getItem: (key: string) => mem[key] ?? null,
      setItem: (key: string, value: string) => { mem[key] = value; },
      removeItem: (key: string) => { delete mem[key]; },
      clear: () => { Object.keys(mem).forEach(k => delete mem[k]); },
      key: (index: number) => Object.keys(mem)[index] ?? null,
      get length() { return Object.keys(mem).length; },
    };
  }
}

export const supabase = createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: createSafeStorage(),
      storageKey: `sb-${extractProjectId(SUPABASE_URL)}-auth-token`,
      flowType: 'pkce',
    }
  }
);
